Update Dockerfile
hassio-addons/addon-unifi pull request #374
Opened 2022-08-06 14:59 UTC by rsnodgrass

# Proposed Changes

* Updated to [Unifi Network Application 7.2.91](https://community.ui.com/releases/UniFi-Network-Application-7-2-91/cdac73f0-7426-4276-ace8-8a96c656ba65#comment/8313ab49-11b8-4c92-9a1c-5c5328d46104) (2022-07-26)

2022-08-06 15:02 UTC, rsnodgrass commented
Label: dependencies (or maintenance)

2022-08-08 10:53 UTC, frenck requested changes

2022-08-08 10:53 UTC, frenck commented on unifi/Dockerfile
> +        "https://dl.ui.com/unifi/7.2.91-85c367a4aa/unifi_sysvinit_all.deb" \
This is a release candidate, and not a stable release.
We don't ship RCs in the add-on.

2022-08-08 10:53 UTC, frenck commented
Closing this PR as it is not upgrading to a stable version.

2022-08-08 10:53 UTC, closed without merging